volumes:
  # mariadb_data:
  mysql_data:


networks:
  baota_net:
    external: true

services:
  app:
    build:
      context: ..
      dockerfile: docker-config/Dockerfile
    container_name: laravel-app-dev
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    ports:
      - "8000:8000"
    command: sh -c "composer update && php artisan key:generate && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - baota_net

  mysql:
    image: mysql:8.1 # atau mysql:5.7 kalau mau versi lama
    container_name: laravel-mysql-dev
    restart: unless-stopped
    ports:
      - "13307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistem_laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - baota_net
