volumes:
  # mariadb_data:
  mysql_data:


networks:
  baota_net:
    external: true

services:
  app:
    build:
      context: ..
      dockerfile: docker-config/config/docker/Dockerfile
    image: laravel-internal-sistem-app-prod
    container_name: laravel-app-prod
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - baota_net

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx-prod
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - baota_net
    depends_on:
      - app

  # mariadb:
  #   build:
  #     context: ..
  #     dockerfile: docker-config/config/database/mariadb/Dockerfile
  #   image: laravel-internal-sistem-mariadb-prod
  #   container_name: laravel-mariadb-prod
  #   restart: unless-stopped
  #   ports:
  #     - "23306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: sistem_laravel
  #     MYSQL_USER: laravel
  #     MYSQL_PASSWORD: laravel_password
  #   volumes:
  #     - mariadb_data:/var/lib/mysql
  #   networks:
  #     - baota_net

  mysql:
    build:
      context: ..
      dockerfile: docker-config/config/database/mysql/Dockerfile
    image: laravel-internal-sistem-mysql-prod
    container_name: laravel-mysql-prod
    restart: unless-stopped
    ports:
      - "13307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistem_laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - baota_net
